// The fixed migration scope from feature-tracker-export (9).csv plus confirmed
// migration features from later planning/export data. Portfolio imports can
// contain additional work without expanding this catalogue automatically.
export const MIGRATION_FEATURE_NAMES = [
  "Customer handover and SPI Team Handover",
  "Sfr cards",
  "Missing file ingestions",
  "Enhance power automate flow",
  "CW, NESA, UAC Data migration",
  "Historical data migration",
  "First Nations Report",
  "Skills Overview Dashboard",
  "Removed S&S Providers Dashboard",
  "Payment Allocation History",
  "Datasheet Automation dataset",
  "A&T Monthly report",
  "A&T Roadmap Performance Dashboard",
  "A&T Skills Alignment Dashboard",
  "Apprenticeship and Traineeship Approvals - VETMMGG",
  "Apprenticeship Provider",
  "Continuing Apprentices and Trainees Placement Service (CAPS)",
  "Regional Training Services Monitoring",
  "Skills Program DataModel",
  "NSW Skills Outcomes Dashboard",
  "SNAP A&T",
  "Training Contract Completion Rate Dashboard",
  "Training Contract Dashboard - Snapshot",
  "Training Contracts Dashboard",
  "VTAS Claims Processed",
  "RTO Performance Dashboard",
  "S2C - Qualification & CAP Allocation File Validation",
  "S2C File validations",
  "VET Public Dashboard for ITABS",
  "Part Qualification Report",
  "Regional Industry Education Partnership",
  "Skills Performance Monthly Snapshot",
  "S&S Enrolments and Subsidy",
  "Skills Program Report",
  "Trade Pathways",
  "VET Executive Summary",
  "VET Performance Dashboard",
  "Aboriginal VET Dashboard",
  "Customer Service Operations Invoices and Payment Vouchers",
  "FFS Snapshot",
  "NPA Progress Against Benchmark Dashboard",
  "Program Stream Participant Frequency",
  "Rebuilding Skills North Coast",
  "Regional Office Participation by Postcode",
  "Regional Office provider allocated qualification usage",
  "GTO Recruitment and EPP Head Start Programs Dashboard",
  "S&S Commencements by Providers, Stream and Regions",
  "S&S Completion Rates",
  "S&S Fee Waiver Analysis",
  "S&S RTO Data Submission Monitoring",
  "Smart and Skilled Dashboard",
  "Smart and Skilled Part Qualification",
  "SNAP S&S",
  "TPPPQ Dashboard",
  "TPPPQ RTO Performance Dashboard",
  "FFS_GF",
  "Low Female Engagement Dashboard",
  "Productivity Bootcamp Dashboard",
  "Region Town Snapshot",
  "Region Town Snapshot home",
  "TAFE Block Funding Dashboard",
  "Vacancy Rate Dashboard",
  "Student Journey Survey - RTO",
  "Student Journey Survey",
  "SJS - CANS Data and Stop words ingestion",
  "SJS RTO Dashboard - Internal EL",
  "ACE Homepage",
  "NAT Files View",
  "Outcome Analysis",
  "Program Progress Report",
  "Provider Performance Summary",
  "Subject Enrolment Detail by Financial Year",
  "Overpayment Report",
  "Provider Risk Dashboard_QA Team",
  "QA Performance Monitoring Sampling",
  "Central and Northern Sydney TSNSW A&T Activity",
  "Smart and Skilled - Prequalified RTOs",
  "Smart and Skilled Providers",
  "VET Student Outcomes Snapshots",
  "Migration of database objects",
  "Ingestion in Edulake Data Tier - ABS Data ingestion",
  "Ingestion in Edulake Data Tier - NCVER Files Ingestion",
];
